{% set name = "pymer4" %}
{% set version = "0.7.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
    git_url: ../  # to enable GIT_X_Y env vars

build:
    # script: python setup.py install --single-version-externally-managed --record=record.txt
    script: pip install . -vv --no-deps
    # abandoned conda build GIT_BUILD_STRING env variable
    string: g{{ environ.get("GIT_ABBREV_COMMIT", "no_git_abbrev_commit") }}_{{ environ.get("PKG_BUILDNUM", "no_pkg_buildnum") }}

requirements:

  host:
    - python  # else test section fails during TravisCI conda build
    - pip

  # TODO: cleanup up any pins no longer needed
  run:
    - python >=3.6
    - deepdish >=0.3.6
    - joblib # >=0.11
    - matplotlib >=3.0
    - numpy # >=1.16.0
    - pandas >=1.0
    - patsy # >=0.4.1
    - rpy2 >=3.3.2 # >=3.1.0  from requirements
    - scipy # >=1.2.0
    - seaborn # >=0.9.0
    - six
    - r-base
    - r-lme4
    - r-lmerTest
    - r-emmeans

test:
  imports:
   - pymer4
   - pymer4.models
  requires:
   - pytest

about:
  home: "http://eshinjolly.com/pymer4/"
  license: MIT
  license_family: MIT
  license_file:
  summary: "pymer4: all the convenience of lme4 in python"
  doc_url:
  dev_url:

# extra:
#   recipe-maintainers:
#     - your-github-id-here
