# Get information from pyproject.toml file
# Conda docs: https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#loading-data-from-other-files
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project', {}) %}
{% set project_deps = project.get('dependencies', []) %}
{% set r_deps = pyproject.get('tools', {}).get('rconfig', {}).get('dependencies', []) %}
{% set version_match = load_file_regex(
  load_file="../pymer4/version.py",
  from_recipe_dir=True,
  regex_pattern='__version__ = "([0-9.]+)"') %}
{% set version = version_match[1] %}

package:
  name: {{ project.get('name') }}
  version: {{ version }}

source:
    git_url: ../
    path: ../

build:
  noarch: python
  script: pip install . -vv --no-deps
  string: {{ GIT_DESCRIBE_HASH }}

# Load both Python and R requirements from pyproject.toml
requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    {% for dep in r_deps %}
    - {{ dep }}
    {% endfor %}
    {% for dep in project_deps %}
    - {{ dep }}
    {% endfor %}

# After building test install (not full test-suite)
test:
  imports:
   - pymer4
  requires: 
   - pytest
  commands:
   - python -c "from pymer4.test_install import test_install; test_install()"
   - pytest

about:
  home: "https://eshinjolly.com/pymer4/"
  license: MIT
  license_family: MIT
  summary: "pymer4: all the convenience of lme4 in python"

extra:
  recipe-maintainers:
    - ejolly
