# Get information from pyproject.toml file
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project', {}) %}
{% set min_python = project.get('requires-python') %}
{% set pip_deps = project.get('dependencies', []) %}
{% set conda_deps = pyproject.get('tool', {}).get('pixi', {}).get('dependencies', []) %}
{% set name = project.get('name')%}
{% set version_match = load_file_regex(
  load_file="../pymer4/version.py",
  from_recipe_dir=True,
  regex_pattern='__version__ = "([0-9.]+)"') %}
{% set version = version_match[1] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    git_url: ../
    path: ../

build:
  noarch: python
  script: pip install . -vv --no-deps
  string: {{ GIT_DESCRIBE_HASH }}

requirements:
  host:
    - python
    - pip
    - numpy >=1.20
    - setuptools >=61.0.0
    - setuptools-scm
    - hatchling

# Load both Python and R requirements from pyproject.toml
  run:
    - python {{ min_python }}
    {% for dep, ver in conda_deps.items() %}
    - {{ dep }} {{ ver }}
    {% endfor %}
    {% for dep in pip_deps %}
    - {{ dep.lower() }}
    {% endfor %}

# Run basic import tests and full test suite after building
test:
  imports:
   - pymer4
  commands:
   - python -c "from pymer4 import test_install; test_install()"

about:
  home: "https://eshinjolly.com/pymer4/"
  license: MIT
  license_family: MIT
  summary: "pymer4: all the convenience of lme4 in python"

extra:
  recipe-maintainers:
    - ejolly
