# Get information from pyproject.toml file
# Conda docs: https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#loading-data-from-other-files
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project', {}) %}
{% set pip_deps = project.get('dependencies', []) %}
{% set conda_deps = pyproject.get('tool', {}).get('pixi', {}).get('dependencies', []) %}
{% set name = project.get('name')%}
{% set version = project.get('version')%}

package:
  name: {{ name }}
  version: {{ version }}

source:
    git_url: ../
    path: ../

build:
  noarch: python
  script: pip install . -vv --no-deps
  string: {{ GIT_DESCRIBE_HASH }}

# Load both Python and R requirements from pyproject.toml
requirements:
  host:
    - python
    - pip
    - numpy >=1.20

  run:
    - python
    {% for dep in conda_deps %}
    - {{ dep }}
    {% endfor %}
    {% for dep in pip_deps %}
    - {{ dep }}
    {% endfor %}

# After building test install (not full test-suite)
test:
  imports:
   - pymer4
   - pymer4.models
  commands:
   - python -c "from pymer4.test_install import test_install; test_install()"

about:
  home: "https://eshinjolly.com/pymer4/"
  license: MIT
  license_family: MIT
  summary: "pymer4: all the convenience of lme4 in python"

extra:
  recipe-maintainers:
    - ejolly
