{% set name = "pymer4" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: "{{ data.get('version') }}"

source:
    git_url: ../  # to enable GIT_X_Y env vars
    path_url: ../ # so conda build will grab source to read version

build:
    script: pip install . -vv --no-deps
    # abandoned conda build GIT_BUILD_STRING env variable
    string: py{{environ.get("CONDA_PY", "XX")}}{{environ.get("GIT_ABBREV_COMMIT", "no_git_abbrev_commit") }}_{{ environ.get("PKG_BUILDNUM", "no_pkg_buildnum") }}

requirements:

  host:
    - python {{ python }}
    # - r-base
    # - r-lmerTest
    # - r-base
    - pip
    - numpy >=1.20

  run:
    - python {{ python }}
    - r-lmerTest
    - r-emmeans
    - pandas >=1.1.0
    - numpy >=1.20
    - rpy2 >=3.5.3
    - seaborn
    - matplotlib
    - patsy
    - joblib
    - scipy
    - scikit-learn
    # {% for req in data.get('install_requires', []) %}
    # - {{ req }}
    # {% endfor %}

test:
  imports:
   - pymer4
   - pymer4.models
  requires:
   - pytest
   - black

about:
  home: "https://eshinjolly.com/pymer4/"
  license: MIT
  license_family: MIT
  license_file:
  summary: "pymer4: all the convenience of lme4 in python"
  doc_url:
  dev_url:

# extra:
#   recipe-maintainers:
#     - your-github-id-here
