{% set name = "pymer4" %}
{% set version = "0.7.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
    git_url: ../  # to enable GIT_X_Y env vars

build:
    # script: python setup.py install --single-version-externally-managed --record=record.txt
    script: pip install . -vv --no-deps
    # abandoned conda build GIT_BUILD_STRING env variable
    string: py{{environ.get("CONDA_PY", "XX")}}{{environ.get("GIT_ABBREV_COMMIT", "no_git_abbrev_commit") }}_{{ environ.get("PKG_BUILDNUM", "no_pkg_buildnum") }}

requirements:

  host:
    - python  # else test section fails during TravisCI conda build
    - pip

  run:
    - python >=3.6
    - deepdish >=0.3.6
    - joblib >=0.14
    - matplotlib >=3.0
    - numpy >=1.16
    - pandas >=1.0
    - patsy >=0.5.1
    - rpy2 >=3.3.2
    - scipy >=1.4.0
    - seaborn >=0.10.0
    - r-base
    - r-lme4
    - r-lmerTest
    - r-emmeans

test:
  imports:
   - pymer4
   - pymer4.models
  requires:
   - pytest

about:
  home: "http://eshinjolly.com/pymer4/"
  license: MIT
  license_family: MIT
  license_file:
  summary: "pymer4: all the convenience of lme4 in python"
  doc_url:
  dev_url:

# extra:
#   recipe-maintainers:
#     - your-github-id-here
