# Learn more at https://jupyterbook.org/customize/config.html
title: Pymer4
author: Eshin Jolly
logo: ''

# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: false

latex:
  latex_documents:
    targetname: pymer4.tex

repository:
  url: https://github.com/ejolly/pymer4 
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:  
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  config:
    add_module_names: True
    autosummary_generate: True