name: Conda Build
on:
  push:
    branches:
      - refactor
  workflow_dispatch:
    inputs:
      upload_anaconda:
        description: 'Upload build to anaconda?'
        required: false
        default: 'skip'
        type: choice
        options:
          - 'skip'
          - 'pre-release'
          - 'main'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py_ver: ['3.10', 3.11, 3.12]
        os: [ubuntu-latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.py_ver }}
          channels: conda-forge,defaults
          channel-priority: strict
          activate-environment: build-env
          auto-activate-base: false

      - name: Build & Test 
        shell: bash -el {0}
        run: | 
          conda config --set always_yes yes
          conda config --set bld_path . 
          conda install conda-build anaconda-client
          conda-build ./conda -c https://conda.anaconda.org/conda-forge --verify

      - name: Upload to Anaconda Pre-release?
        if: ${{ ( matrix.py_ver == '3.11' && matrix.os == 'ubuntu-latest' && github.event_name != 'release') || inputs.upload_anaconda == 'pre-release' }}
        shell: bash -el {0}
        env:
            ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: | 
          upload_file=$(conda-build ./conda --output)
          anaconda -t $ANACONDA_TOKEN upload $upload_file -l "pre-release"

      - name: Upload to Anaconda Main?
        if: ${{ ( matrix.py_ver == '3.11' && matrix.os == 'ubuntu-latest' && github.event_name == 'release') || inputs.upload_anaconda == 'main' }}
        shell: bash -el {0}
        env:
            ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: | 
          upload_file=$(conda-build ./conda --output)
          anaconda -t $ANACONDA_TOKEN upload $upload_file -l "main"