name: Conda Build
on:
  push:
    branches:
      - refactor
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py_ver: ['3.10', 3.11, 3.12]
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.py_ver }}
          channels: conda-forge,defaults
          channel-priority: strict
          activate-environment: build-env
          auto-activate-base: false
      - name: Conda info
        shell: bash -el {0}
        run: | 
          conda config --set always_yes yes
          conda install conda-build
      # - name: Conda info
      #   shell: bash -el {0}
      #   run: | 
      #     conda config --set always_yes yes
      #     conda config --set bld_path . 
      #     conda install conda-build anaconda-client
      #     conda-build ./conda -c https://conda.anaconda.org/conda-forge --verify
      - name: Build and Upload Conda Package
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        with:
          meta_yaml_dir: ./conda
          python-version: ${{ matrix.py_ver }}
          user: ejolly
          label: 'pre-release'
          token: ${{ secrets.ANACONDA_TOKEN }}
          overwrite: true
          upload: false