name: Pixi Build
on:
  push:
    branches:
      - refactor
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi & Build Docs
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.42.1
      - run: | 
         pixi run docs-build
         touch docs/_build/html/.nojekyll

      # - name: Deploy docs
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   uses: crazy-max/ghaction-github-pages@v2
      #   with:
      #     target_branch: gh-pages
      #     build_dir: docs/_build/html