name: Pixi Run Tests
on:
  push:
    branches:
      - refactor
  workflow_dispatch:

jobs:
  pixi-docs-build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi & Build Docs
        uses: prefix-dev/setup-pixi@v0.8.3
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        with:
          pixi-version: v0.42.1
      - run: | 
         pix run tests
         pixi run docs-build
         touch docs/_build/html/.nojekyll
         pixi run build
         pixi shell
         echo $ANACONDA_TOKEN

      # - name: Deploy docs
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   uses: crazy-max/ghaction-github-pages@v2
      #   with:
      #     target_branch: gh-pages
      #     build_dir: docs/_build/html